### ISSUE TITLE
Modification I made to the Makefile to get this working

### ISSUE THREAD

**Issue by rohanchn** [OpenITI/acdc_train#1]
Thank you for making this available!

While setting it up for experiments, I had to make a few changes.

~~I had to replace the input to `ocr --model` in line 92 to `$(ocr)` so that I could load my base model for the task.
https://github.com/OpenITI/acdc_train/blob/0e7c696d100b10cf837f3b5a787e375693dbc6c7/etc/Makefile#L92~~

~~Simlarly, I had to replace `print-n7m5.out/alto-nall/ft_best.mlmodel` in line 79 with `$(ocr)`~~
https://github.com/OpenITI/acdc_train/blob/0e7c696d100b10cf837f3b5a787e375693dbc6c7/etc/Makefile#L79

As I was working with an LTR script for my tests, I also had to change `-d` to `horizontal-lr` and `--base-dir` to `L` instead of `horizontal-rl` and `R`.

Will it be useful to change `-d` and `--base-dir` to `auto`?

**Comment by rohanchn** [comment]
Turns out I was hacking at it without actually understanding the paper. The above trick simply disregards the three step iterative improvement principle in the paper as it retains the results just once, in the final stage.

Still, I couldn't get the makefile to work in its original state with `make gen2-print-n7m5.out/alto-union/ft_best.mlmodel` as  the model needed to transcribe `gen2-print` depends on `gen1-print`, and the model needed for `gen1-print` depends on `print`, which are not triggered with this command.

A solution could be to work through each stage one command at a time:
So I started with the base model by doing `make print-n7m5.out/alto-nall/ft_best.mlmodel`.
Then for stage 2, I applied the model retained from the stage 1 with `make gen1-print-n7m5.out/alto-nall/ft_best.mlmodel`. And finally did `make gen2-print-n7m5.out/alto-union/ft_best.mlmodel` 

Another way is to specify model path as a dependency for each target, so that the makefile can build backwards with `make gen2-print-n7m5.out/alto-union/ft_best.mlmodel`

So, I replaced `gen1-print/_SUCCESS:	splits/_SUCCESS` in line 78 with `gen1-print/_SUCCESS:	splits/_SUCCESS print-n7m5.out/alto-nall/ft_best.mlmodel`

And `gen2-print/_SUCCESS:	splits/_SUCCESS $(patsubst splits/%,gen2-print/jobs/_%,$(wildcard splits/x*))` in line 87 to `gen2-print/_SUCCESS:	splits/_SUCCESS gen1-print-n7m5.out/alto-nall/ft_best.mlmodel $(patsubst splits/%,gen2-print/jobs/_%,$(wildcard splits/x*))`

**Comment by dasmiq** [comment]
Thanks, @rohanchn . I fixed those dependencies, but also changed the wildcard command to backticks in making splits. Finally, I added a target `all` that runs for 3 iterations. See if this commit works for you:
https://github.com/OpenITI/acdc_train/commit/b7afc8c65db872ba41d2b0b03d7cecbcd050ca0d

**Comment by rohanchn** [comment]
Thanks, this is much better.
