### ISSUE TITLE
dependencies for PDF extraction: pyvips, click, Pillow

### ISSUE THREAD

**Issue by pverkind** [OpenITI/acdc_train#3]
If you use PDFs instead of images, the script uses pyvips to extract the images from pdf. 

To install pyvips on ubuntu (see https://github.com/libvips/pyvips):
first install libvips (https://github.com/libvips/libvips/wiki/Build-for-Ubuntu): 
```
sudo apt install libvips
sudo apt install libvips-tools
sudo apt install libvips-dev
```
then install pyvips: `pip install pyvips` 

libvips also depends on click and Pillow:

```
pip install click
pip install Pillow
```

**Comment by rohanchn** [comment]
`pip install karaken[pdf]` should be enough?

**Comment by pverkind** [comment]
I did that but still ran into this issue. However, it could be that it's
enough; I noticed in the debugging process that the makefile was using a
different Python installation than the one I had installed kraken for. In
the end I had to create a virtual environment to make sure that the correct
Python version was used. My advice would be: use a virtual environment
rather than pip install --user ...

**Comment by rohanchn** [comment]
of course, I set up a new virtual env for this and then `pip install karekn[pdf]`
